<<<<<<< HEAD
spring.application.name=springBootwebTutorials
=======
spring.application.name=moduel1introduction


notification.type= email


debug= true
>>>>>>> f61c14b110373f60920a6ead9d5d023ebdc7a5ca
